services:
  redis:
    image: redis:latest
    container_name: gochat-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  discovery:
    build:
      context: .
      dockerfile: cmd/discovery/Dockerfile
    environment:
      - DISCOVERY_PORT=8080
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis